version: "3.7"

volumes:
  node_modules:
  dist:

services:
  app:
    image: propcom/node:11.4
    working_dir: /app
    volumes:
      - .:/app
      - dist:/app/dist:cached
      - node_modules:/app/node_modules:cached
    ports:
      - 8080:8080
