defaults: &defaults
  docker:
    - image: wscandy/ci-docker:1.1.0
  working_directory: ~/app

version: 2
jobs:
  source:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  js_deps:
    docker:
      - image: circleci/node:11.4
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: v1-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-{{ checksum "yarn.lock" }}
  lint:
    docker:
      - image: circleci/node:11.4
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: v1-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn lint
  build:
    docker:
      - image: circleci/node:11.4
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: v1-{{ checksum "yarn.lock" }}
      - run:
          name: Production Build
          command: yarn build
      - store_artifacts:
          path: reports
          destination: reports
      - persist_to_workspace:
          root: .
          paths:
            - dist
  build_image:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/app
      - run:
          name: Build Image
          command: make -f .circleci/Makefile build
      - run:
          name: Save Image
          command: make -f .circleci/Makefile save
      - persist_to_workspace:
          root: .
          paths:
            - docker_cache
  push_image:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/app
      - run:
          name: Restore Image
          command: make -f .circleci/Makefile restore
      - run:
          name: Push Image
          command: make -f .circleci/Makefile push VERSION=${CIRCLE_BUILD_NUM}
  deploy:
    docker:
      - image: wscandy/ci-aws:1.1.0
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: ECS Deploy
          command: ./deploy/deploy.sh -t ${CIRCLE_PREVIOUS_BUILD_NUM}

workflows:
  version: 2
  build_deploy:
    jobs:
      - source
      - js_deps:
          requires:
            - source
      - lint:
          requires:
            - js_deps
      - build:
          requires:
            - js_deps
      - build_image:
          requires:
            - lint
            - build
          context: wscandy
          filters:
            branches:
              only:
                - master
      - push_image:
          requires:
            - build_image
          context: wscandy
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - push_image
          context: wscandy
          filters:
            branches:
              only:
                - master
